defaults: &defaults
  oauth:
    client_id: 'dffd069fa92096022628a1f7eb174bc85d90278b8c90ec7ebadfbd94924bd2b8'
    secret: 'e1805141c81c496e4779371f41263c9f74ac2ffd3728302296b8af10b64d9c9b'
    scope: 'read_products read_orders'
    redirect_uri: 'http://localhost:3000/app/callback'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  oauth:
    client_id: 'f4dsf34324j55cc1531e'
    client_secret: 'a7f63f3dsfsdjfmk30474321c5134ba84920afd5'
    scope: 'read_products read_orders'
    redirect_uri: 'http://localhost:3000/app/callback'
